[tool.poetry]
name = "PlaywrightCapture"
version = "0.1.0"
description = "A simple library to capture websites using playwright"
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]

[tool.poetry.dependencies]
python = "^3.8"
playwright = "^1.21.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.942"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
