[tool.poetry]
name = "PlaywrightCapture"
version = "0.1.0"
description = "A simple library to capture websites using playwright"
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]

[tool.poetry.dependencies]
python = "^3.8"
playwright = "^1.21.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
mypy = "^0.942"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = 3.8
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = false
strict_optional = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true

show_error_context = true
pretty = true
